### ISSUE TITLE
Can't update the DB

### ISSUE THREAD

**Issue by 2001asjad** [2001asjad/TestCodes#4]
Currently what `collect_data.py` does is it fetches GitHubIssues from the desired repository and stores the content of these fetched issues in the new folder as shown in the code.
And it updates the database `DeepAQAtikData` with keys and values as described in the file `collect_data.py`.
What `regex.py` does it extracts all the "`" quoted outputs from those stored files and stores them in the new file. What I am trying to do is after extracting the "`" quoted data, I want to add to the MongoDB database with a new key( "issue_content_console_path") to the value (where the extracted data is stored by `regex.py`) but it isn't happening as of now.
FYI @AmaaniGoose

**Comment by AmaaniGoose** [comment]
The main issue I see here is with the file paths. The new folder needs to be created in order for it to work as intended. 

I've done that and it imported 1815 files which took 36 seconds to do. 

Then created the results folder and ran the regexify code. That printed a large amount of output to the file. Since I can't see the db, I cant say if its working correctly or not. Review the changes once.
